copy jod.tex            C:\jodsvn\joddictionary\jodtex
copy jodbib.bib         C:\jodsvn\joddictionary\jodtex            
copy jodamble.tex       C:\jodsvn\joddictionary\jodtex            
copy jodappendices.tex  C:\jodsvn\joddictionary\jodtex            
copy jodbest.tex        C:\jodsvn\joddictionary\jodtex            
copy jodcommon.tex      C:\jodsvn\joddictionary\jodtex\              
copy jodexample.tex     C:\jodsvn\joddictionary\jodtex\            
copy jodfiles.tex       C:\jodsvn\joddictionary\jodtex\            
copy jodhung.tex        C:\jodsvn\joddictionary\jodtex\            
copy jodintro.tex       C:\jodsvn\joddictionary\jodtex\            
copy jodscripts.tex     C:\jodsvn\joddictionary\jodtex\           
copy jodtitlepage.tex   C:\jodsvn\joddictionary\jodtex\           
copy jodtutor.tex       C:\jodsvn\joddictionary\jodtex\           
copy jodvcsys.tex       C:\jodsvn\joddictionary\jodtex\          
copy jodwords.tex       C:\jodsvn\joddictionary\jodtex\          
copy jodgraphics\j6folders.eps      C:\jodsvn\joddictionary\jodtex\jodgraphics\   
copy jodgraphics\j6labs.eps         C:\jodsvn\joddictionary\jodtex\jodgraphics\
copy jodgraphics\j7folders.eps      C:\jodsvn\joddictionary\jodtex\jodgraphics\
copy jodgraphics\j7labs.eps         C:\jodsvn\joddictionary\jodtex\jodgraphics\
copy jodgraphics\jodRGBcube.eps     C:\jodsvn\joddictionary\jodtex\jodgraphics\
copy jodgraphics\joddot.eps         C:\jodsvn\joddictionary\jodtex\jodgraphics\
copy jodgraphics\jodlittlecube.eps  C:\jodsvn\joddictionary\jodtex\jodgraphics\
copy jodgraphics\zippy.eps          C:\jodsvn\joddictionary\jodtex\jodgraphics\ 
pause